### PR TITLE
Final check paola

### PR DESCRIPTION
**Pull request by iamaleaf**
#8 
Final check Paola

### CODE REVIEW

**Comment by merforga** [comment]
.idea file got committed somehow. O.O. Other than that should be ok moving forward.

**Comment by iamaleaf** [comment]
I.. have no idea why/what that is. Is this something I should be manually unchecking? I just left it with the default settings when pushing it

**Comment by merforga** [comment]
.idea files are the local project files so are not needed in this repo (since they're only relevant for your local environment). Technically the .gitignore file should remove them from all the commits but for some reason this didn't Oo. 

Just something to be mindful of for future pushes.

**Comment by iamaleaf** [comment]
Cool, will keep it in mind. Thanks!

**Pull request closed without merging**
